### ISSUE TITLE
Error: commitTime: stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by calmdev** [walmartlabs/generator-release#20]
Have you guys seen this before? I'm having a hard time finding information about it. 

Running on OSX 10.9.2 with 4GB ram:

![screen shot 2014-04-01 at 8 48 48 pm](https://cloud.githubusercontent.com/assets/461249/2586450/befc3d8a-ba00-11e3-8c3a-e200557f7517.png)

**Comment by kpdecker** [comment]
Released in 2.4.0
