### ISSUE TITLE
GitHub Enterprise Installation

### ISSUE THREAD

**Issue by pantocrator27** [walmartlabs/generator-release#28]
Would it be possible to allow this module to publish to an private enterprise GitHub installation by making the publishing function configurable?

**Comment by kpdecker** [comment]
Just ran into this myself. I'll look into it and see what I can do for a PR.

**Comment by pantocrator27** [comment]
Many thanks.  I can help test if needed!

**Comment by pantocrator27** [comment]
That is awesome!!!  I will be sure to check it out.  Many thanks!

**Comment by kpdecker** [comment]
Released in 2.4.0
